In [3]:
from google.colab import files
uploaded = files.upload()

Saving data.csv to data (4).csv

In [4]:
import io
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import pickle
df = pd.read_csv(io.BytesIO(uploaded['data.csv']))
df.head()

              R_fighter       B_fighter  ... B_age R_age
0          Henry Cejudo   Marlon Moraes  ...  31.0  32.0
1  Valentina Shevchenko     Jessica Eye  ...  32.0  31.0
2         Tony Ferguson  Donald Cerrone  ...  36.0  35.0
3         Jimmie Rivera        Petr Yan  ...  26.0  29.0
4           Tai Tuivasa   Blagoy Ivanov  ...  32.0  26.0

[5 rows x 145 columns]

In [5]:
df.columns

Index(['R_fighter', 'B_fighter', 'Referee', 'date', 'location', 'Winner',
       'title_bout', 'weight_class', 'no_of_rounds', 'B_current_lose_streak',
       ...
       'R_win_by_KO/TKO', 'R_win_by_Submission',
       'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms',
       'R_Reach_cms', 'R_Weight_lbs', 'B_age', 'R_age'],
      dtype='object', length=145)

Cleanup the data

In [6]:
df.isnull().values.sum()

95390

In [0]:
categorical_columns_missing = ['Referee']
impute_missing=SimpleImputer(missing_values=np.NaN, strategy='most_frequent')
df[categorical_columns_missing] = impute_missing.fit_transform(df[categorical_columns_missing])

In [0]:
numerical_columns_missing = ['R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs','B_age','R_age'] #these are the columns that are (somewhat) important for further analysis and therefore have to be cleaned up. There are, as shown in the cell above, several columns with NaN-values but they are not of importance for further analysis or can be 0 by purpose (like e.g. B_draw)
impute_missing=SimpleImputer(missing_values=np.NaN, strategy='mean')
df[numerical_columns_missing] = impute_missing.fit_transform(df[numerical_columns_missing])

In [0]:
df.to_csv('data_clean.csv')
files.download("data_clean.csv")
df = pd.read_csv('data_clean.csv')